### ISSUE TITLE
"Multithreading"

### ISSUE THREAD

**Issue by KLVN** [0xredviper/LoovoAutoLike#2]
It takes much time and data to load 1 user, like that one and load again 1 other user. Is it possible to have some kind of "multithreading" where the script is crawling e.g. 10 users and while liking them very fast (because it doesn't have to reload the id for every user again) it is already crawling another list of 10 users.
Why I need it? My connection is not the fastest and that's why I can only like ~5000 users per hour

**Comment by danieleargento** [comment]
Regarding the like/unlike game, the system assign to you a new user id when you like the current so, to have a new user to like, you must first like the current user.
It is possible to achieve what you want, you must to do a standard search in the site, parse the results and like that users but the code must to be heavily modified. Keep in mind that the system allow you to like only a certain number of people in one day.

**Comment by KLVN** [comment]
> you must to do a standard search in the site, parse the results and like that users

I also thought about this creating of a big database with user id's and then mass-liking them all

> the system allow you to like only a certain number of people in one day

There's the option to buy VIP for 1h with credits and my aim is to make the most of it :see_no_evil: 

I'll take a look at this. Thanks :)

**Comment by KLVN** [comment]
Do you know a program that is scraping data from JSON/the Lovoo API?
I built a small iMacros macro that scrapes all URLs and in Excel I would cut them so there are just the ID's, but it may be not the most efficient way.
